### ISSUE TITLE
Many issue/problems with releases 23.01.22-HF01 and 23.01.22-HF02. Downgrade to 23.01.14 

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#153]
Hi,

I'm sorry but I have to note that the last releases (23.01.22-HF01 and 23.01.22-HF02) were really a disaster. They broke many things!!
I tried the update 3 times but now I'm stuck on the stable release
`jokobsk/pi.alert:23.01.14`

When you have solved the many problems I will try one last update.
The detail of the devices is still undefined for me..
![Cattura](https://user-images.githubusercontent.com/5001932/214148076-c77b20aa-bf25-4af0-883a-8680387b5547.PNG)

**Comment by jokob-sk** [comment]
Hi there, 

The issues you are mentioning are fixed in  23.01.22-HF02. Please try to:

1) Remove the docker container
2) Remove the docker image
3) Run `sudo docker-compose up -d` (this will re-download the latest image.

If using Synology, this caching of images seems to be a common issue, e.g. as explained here by another user: https://github.com/jokob-sk/Pi.Alert/issues/151

**Comment by jokob-sk** [comment]
Seems to be resolved > Closing
