### ISSUE TITLE
Add support for external values in the conf file

### ISSUE THREAD

**Issue by wschaef** [jokob-sk/Pi.Alert#182]
**Is your feature request related to a problem? Please describe.**
It is a good practice to commit conf file to git. Storing secrets like SMTP_PASS in git is not a good practice. 

**Describe the solution you'd like**
Can you please add support for external values in the conf file. First option would be to read from file like "/run/secrets/smtp_pass". Second option would be to read from environment variable.

**Describe alternatives you've considered**
I'm not skilled with python so I can't create a proper merge request.

**Additional context**
The change would be around this line:     exec(code, {"__builtins__": {}}, c_d)  351:pialer.py.

**Comment by jokob-sk** [comment]
Hi @wschaef !

Thanks for using this image and the suggestion!

Regrettably I don't plan to implement this unless there are more users interested and/or it could be part of my [sponsorship drive as an unlock-able tier](https://github.com/sponsors/jokob-sk) :) . 

You can use throwaway accounts for things such as SMTP servers instead of your main ones as a workaround. 

Thanks!
j
