### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Fabaderheld** [jokob-sk/Pi.Alert#38]
Hi,

I got it running, only that I get greeted with a password prompt and instructions on how to reset. But the script ```reset_password.sh``` in the ```config``` folder is missing. Any Ideas?

![image](https://user-images.githubusercontent.com/4440238/180634948-11eb9fee-d889-43c5-aa07-fdb6c2d9c8cb.png)

thanks

Faba

**Comment by jokob-sk** [comment]
Hey! According to: https://github.com/jokob-sk/Pi.Alert#front

Just set `PIALERT_WEB_PROTECTION = False`

Default PWD is `123456`

**Comment by jokob-sk** [comment]
Also pull the latest image (I updated it an hour back if you use an older one)

**Comment by Fabaderheld** [comment]
So this was added an hour ago? Because I played around yesterday and there was no authentication 😄 .

```PIALERT_WEB_PROTECTION = True`` is default?

the pwd does not work.

regards

Faba

**Comment by jokob-sk** [comment]
Please delete the image, pull the latest one (I published it today, so anything from yesterday is outdated) and add `PIALERT_WEB_PROTECTION = False` into `pialert.conf`

**Comment by jokob-sk** [comment]
@Fabaderheld did you get it working?

**Comment by Fabaderheld** [comment]
Just pulled it again, It works only when ```PIALERT_WEB_PROTECTION``` is set to ```False```. The password ```1234566``` is not working nor can I reset it via the script

**Comment by jokob-sk** [comment]
Cool, if you want to use the default password you need to include this line into your `pialert.conf` file:

https://github.com/jokob-sk/Pi.Alert/blob/7057e059259a82f45036e8b5f46cbd4154fec49f/config/pialert.conf#L17

That's the HASH for the password `123456`

Otherwise yes, you need to run the script. Hummm... I might add it as a configurable variable in the docker setup workflow later
