### ISSUE TITLE
Quering device info, informations are not displayed

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#421]
Built on: 2023-09-10 | Version: v23.9.10

If I open a Device I see the message "Quering device info.." The informations are not displayed (also after 10 Minutes...)

![Bildschirmfoto 2023-09-10 um 13 45 54](https://github.com/jokob-sk/Pi.Alert/assets/22064392/4e784a06-a552-49d5-a71e-b9185e3a1bce)

**Comment by jokob-sk** [comment]
Can you please share any errors that come up in the browser console as per:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md

Thanks!

**Comment by ace16vitamine** [comment]
Spooky: I cleared the log and now the page is displayed. I keep you informed if it is again an issue

**Comment by SunTrustDev** [comment]
I'm getting this right now on my installation.
![immagine](https://github.com/user-attachments/assets/49087ccc-afaa-45a7-a29f-c7e72ddbbc9c)
There is an error in console, pointing to the deviceDetails.php file at line 1551:
![immagine](https://github.com/user-attachments/assets/de7f9f5b-7db0-4714-a213-8061cf73a5a9)
It seems to be a translation related issue, since the apostrophe is not being escaped correctly.

**Comment by jokob-sk** [comment]
Hi @SunTrustDev,

This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.
Thanks in advance,
j

**Comment by SunTrustDev** [comment]
Hi @jokob-sk, thanks for the great job.
I installed the new dev version on my end and everything seems to work smoothly!
I had some cache troubles on firefox, but after cleaning multiple times I could finally access the pages.
Result:
![immagine](https://github.com/user-attachments/assets/13f56e5b-f502-42e9-aa43-b351aebb3fac)

Thanks!!

**Comment by jhonatn** [comment]
I just found another way for this to happen. If you import a devices.csv with the wrong date format, it will import it but the details screen will never work, stuck in the same way as SunTrustDev's screenshot

**Comment by jokob-sk** [comment]
Thansk @jhonatn . I've added this note in the docs:

> The database and device structure may change with new releases. When using the CSV import functionality, ensure the format matches what the application expects. To avoid issues, you can first export the devices and review the column formats before importing any custom data.
