### ISSUE TITLE
Would it be possible to have another user in read-only mode?

### ISSUE THREAD

**Issue by jruiz94** [jokob-sk/Pi.Alert#453]
First of all I want to give a huge thank you for this project. For my needs it's perfect 🙌 

This is more a question rather than a feature request. Would it be possible for another user to log in as read-only or something to see the devices? Or any way to check the database and show it using another software or something.

I want to give the insights of the devices connected to another person, but I don't want that person to fiddle with the settings or change names of the devices.

**Comment by jokob-sk** [comment]
Thanks for the encouragement 😄

Creating a read only user implies a lot of underlying logic for permission management and I am not too keen on that (maintenance of the code, testing possible edge cases etc). This is only I'd consider with generous recurring sponsorships since the overhead is significant if implemented thoughly and I'd have to sacrifice other more valuable features that I plan to implement. 

However, there are alternatives. 

Depending on the format you could simply send the user a link to the API endpoints or to the automatically generated devices.csv file created by the CSV backup plugin. 

More info on the API here https://github.com/jokob-sk/Pi.Alert/blob/main/docs/API.md

Let me know your thoughts, 
J

**Comment by jruiz94** [comment]
> Creating a read only user implies a lot of underlying logic for permission management and I am not too keen on that (maintenance of the code, testing possible edge cases etc). This is only I'd consider with generous recurring sponsorships since the overhead is significant if implemented thoughly and I'd have to sacrifice other more valuable features that I plan to implement.
Yes I completely understand, don't worry! I was asking just in case.
> However, there are alternatives.
> 
> Depending on the format you could simply send the user a link to the API endpoints or to the automatically generated devices.csv file created by the CSV backup plugin.
> 
> More info on the API here https://github.com/jokob-sk/Pi.Alert/blob/main/docs/API.md
> 
> Let me know your thoughts, J
Yes this suites my needs, I'll check if I can do something more user friendly but from what I can see, querying the API for the `table_devices.json` seems perfect for what I want to do.

Thanks again for the help and the quick response! Have a nice week! :D

**Comment by jokob-sk** [comment]
Happy to help 😉 have a great day
