### ISSUE TITLE
Issues in PIHOLE plugin

### ISSUE THREAD

**Issue by ftrueck** [jokob-sk/Pi.Alert#479]
The plugin PIHOLE crashes the whole docker container, when the config is not correct.

Example: 
- pihole-FTL.db does not exist and plugin is enabled => Docker container crashes
- The SQL Query for pihole is missing a check on the end of the query => AND na.ip <> null;
- The plugin is configured to run once and conditions 1 or 2 are met => Docker container crashes few seconds after boot up

**Comment by jokob-sk** [comment]
Hi @ftrueck 

Thanks for the question.

> - pihole-FTL.db does not exist and plugin is enabled => Docker container crashes 

Thi sis expected behavior as I can't influence how the user configures their docker environment. I could check if the file exists, but I would even say that it would hide the issue and users this way fix their mappings earlier. Happy to hear your thoughts. 

- I will add the `AND na.ip <> null;` to the end of the SQL query once PR #470 is merged not to cause conflicts.

Cheers,
j

**Comment by ftrueck** [comment]
I suggest to gracefully fail instead of exiting the whole application. In case of misconfiguration it would help if the container is not crashing, because not everyone knows how to shell into the container to fix the config file manually.

**Comment by jokob-sk** [comment]
good point on chnaging the configuration after the crash - will have a look into it as well

**Comment by jokob-sk** [comment]
Released in 23.11.11
