### ISSUE TITLE
Add support for large networks

### ISSUE THREAD

**Issue by gpend** [jokob-sk/Pi.Alert#485]
**Is your feature request related to a problem? Please describe.**
when scanning my network that was recently changed from a /24 (that worked) to a /16 it takes down my entire network on the second scan

**Describe the solution you'd like**
my understanding from https://github.com/leiweibau/Pi.Alert/commit/feb3eab3cd6ae2f94ac35662aa7e8371367cd04e is that the bandwidth needs to be reduced, types and times of scans need to be adjusted

**Describe alternatives you've considered**
leiweibau/Pi.Alert but it does not support docker

**Comment by leiweibau** [comment]
My humble contribution to the topic.
The scan parameters are largely the same for me as for @jokob-sk, with the exception that I have increased the bandwidth for me. However, @jokob-sk also offer some additional active scans, which are not available on my fork. This must also be taken into account. If all these scans flood the network, then you are no longer using Pi.Alert as a scanner, but as a denial-of-service tool. Monitoring should be subtle and not like a bulldozer 😉.
Since I myself, until a few months ago, used a /16 network, I would also like to share with you considerations that led me to change this:
- do I really need a network with 65000+ hosts?
- how can I make the work easier for the tools I want to use (smaller networks, means faster work).
- there is not only /16 or /24 (I chose a /20)

From experience an arp-scan of a /16 with 3 retries and a bandwidth of 256k took, I think, about 2-3min. Since @jokob-sk uses 6 retries and a smaller bandwidth, it takes longer. Possibly the scans build up here.

**Comment by jokob-sk** [comment]
@leiweibau - thanks for the contribution and explanation! 😄

@gpend - I added a setting to make arp-scan args configurable. it's available in the `pi.alert_dev` image. Please test it and let me know if that works for you (please backup everything first as the dev image alters DB and config files). 

https://github.com/jokob-sk/Pi.Alert/commit/ae7533cec06c427b431f13a981e149547f6ee483

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/a6eeef12-8f6a-40ec-b396-45be24fcb981)

**Comment by jokob-sk** [comment]
Released in 23.11.11
