### ISSUE TITLE
[request] Auto-maintenance of log files

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#494]
Could a ~100MB log file cause problem? 
I had this weird behavior where the Maintenance page would hang, it opened up "fine" but when I tried to press any of the tabs nothing would happen.
After I removed it everything went back to normal.
Should I clean the log once in a while or maybe it was just some junk in the data itself that caused the problem?

_Originally posted by @Nionor in https://github.com/jokob-sk/Pi.Alert/discussions/488_

__________________________________________________________________________________

I know the current logging approach generates big log files if a verbose log level, such as 'verbose' or 'debug' is set. I'm thinking about two options:

1. Auto delete and keep only N lines (configurable) of logs
2. Purge file completely on user-defined schedule set to once a week by default

Any suggestions or concerns?

_Originally posted by @jokob-sk in https://github.com/jokob-sk/Pi.Alert/discussions/488#discussioncomment-7407713_

**Comment by lorki97** [comment]
I have not taken a deep dive into the Python logging in the application, but if the logging is somewhat centralized then Python already supports log rotation with some special file handlers:

- File size based rotation: https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
- Time based rotation: https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler

This way users can influence how big a single log file can become and how much log files the system should keep. Some might prefer the file size rotation due to exactly knowing how much space the log files can take up at most. Others like time based rotation to e.g. have a log file for each day and keep logs for 7 days.

**Comment by jokob-sk** [comment]
Thanks for the input! Implemented a basic maintenance plugin with an option to specify how many lines of logs to keep. It can be extended further with log rotation etc. in the future. https://github.com/jokob-sk/Pi.Alert/commit/c91e428e7782e83a106e27db52bd9cb57297700c

**Comment by jokob-sk** [comment]
Released in 23.11.11
