### ISSUE TITLE
Continuous down alerts

### ISSUE THREAD

**Issue by gkovacsp** [jokob-sk/Pi.Alert#51]
My device went down and then came back later. I've received a down alert via email but the down alerts never stopped ever since.
UI shows device is online, history shows it is connected.
I've switched off down alerts until it is fixed but the down alerts are still coming.
I've deleted the container and the image, pulled it again but the down alerts are still coming.

Device is shown as connected:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1654787/181741352-2f7f6a65-4849-406b-b75f-ab34e9bf55a7.png">

History shows it is connected
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/1654787/181741406-2f926e3d-f2f9-4b95-9037-7cdfba737968.png">

Notifications are off
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1654787/181741482-dc120533-cc09-4e28-be14-52af5daeb606.png">

Yeat a new email every 5 minutes
<img width="577" alt="image" src="https://user-images.githubusercontent.com/1654787/181741535-0278beb8-f416-4dd4-8113-b3c385b34620.png">

**Comment by jokob-sk** [comment]
Hey,

At first, please backup your DB before trying to resolve the issue. 

I didn't come across this issue on my side, however you can try pulling an older image to see, if the issue persists, e.g this built 5 days ago: https://registry.hub.docker.com/layers/pi.alert/jokobsk/pi.alert/sha-7057e05/images/sha256-f0ef59d0b732f00cf750c204ae1815994bdfce51a88c75bda35294c01710ba5b?context=explore

I think however this is because of some weirdly logged event in the DB.

If you don't mind losing the Presence history, you can try deleting events under Maintenance > Tools to see if this solves the issue:

![image](https://user-images.githubusercontent.com/96159884/181745691-402f90c1-87cc-4ecf-82ee-25f6db61d141.png)

I had a similar issue before, but it was due to having 2 deployments (2 docker images of Pi.Alert running at the same time on two different servers.

**Comment by gkovacsp** [comment]
Deleting the problematic device did not help, once is back the alerts are back. I'll try the more destructive method later.

**Comment by jokob-sk** [comment]
@Final-Hawk  Just submitted a pull request which might fix the issue - and the image will be up in about 10 minutes

**Comment by gkovacsp** [comment]
> @Final-Hawk Just submitted a pull request which might fix the issue - and the image will be up in about 10 minutes

Alerts are still coming. 
When it finds again the previously deleted device it will find all its previous presence information, so probably the complete deletion will help - which I'm still reluctant to do :) I'll change my email password to stop the alert tsunami.

**Comment by gkovacsp** [comment]
I've deleted all activities and there are no more alerts. Would have been great to clear the activities only for a specific device.

**Comment by jokob-sk** [comment]
I've added this as an option in Device Details. The new docker image will be on Docker hub in about 15 minutes:

https://github.com/jokob-sk/Pi.Alert/commit/a7709ce6e17e5645047e39275c0acc478aed4448

**Comment by gkovacsp** [comment]
Great, I've rolled back the db, deleted only these two devices and the alerts are gone. Thanks a lot!

**Comment by jokob-sk** [comment]
Glad it helped!
