### ISSUE TITLE
Notifications: IP changed event being triggered even when the IP doesn't change

### ISSUE THREAD

**Issue by jsmith432** [jokob-sk/Pi.Alert#530]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Getting a notification for Event Type: IP Changed for the same device with no changes to IP. Some of these devices have static IP, so the IP would not have changed.

### Expected Behavior

Get an IP changed notification only if that mac address is associated with a new IP.

In this picture MAC, IP, and Device name are all the same: 

![Screenshot 2024-01-06 123003](https://github.com/jokob-sk/Pi.Alert/assets/4900328/525dc2e9-09eb-480f-88e3-698e72061a85)

### What branch are you running?

Dev

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @jsmith432 ,

I've tried to reproduce the behavior with the arp-scan plugin with the following settings, however, I couldn't get the same behavior on my end: 

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/532afdc7-7b13-47e4-874d-d22ce8595f3c)

Could you please share your config file or provide steps how to reproduce the issue?

**Comment by jsmith432** [comment]
hi! thanks for your reply. The only watched-changed I have is for DHCP leases. I have not turned that configuration on for ARP. I am assuming is having something to do with having the 3 scans: arp, DHCP leases and pi-hole devices. now I don't understand why would dhcp leases have been triggered by a static IP?

[pialert.conf.txt](https://github.com/jokob-sk/Pi.Alert/files/13866796/pialert.conf.txt)

**Comment by jokob-sk** [comment]
Thank you for the details!
What might be happening is that the different plugins might store the IP address slightly differently, for example, there might be a space stored somewhere which then is technically a different IP (at least a different string) as one without a white space. That's my theory - I will have a closer look later in the week or over the weekend.

**Comment by andrewlow** [comment]
Oh.. I was coming here because I have a similar situation - but I know why it's happening to me. (it would be good to know how to fix it).

I run docker and have setup macvlan to allow the assignment of containers to their own IP addresses. I wrote about this here: https://lowtek.ca/roo/2020/docker-and-macvlan-networking-ipv4/

I reserve an address to act as a 'shim' between the host machine, and the new sub-network I've created. In the blog post I am reserving `192.168.1.67` as the shim/bridge address.

What does this mean for `arp-scan`? 

```
$ sudo arp-scan --interface enp3s0 --localnet

192.168.1.67       1c:1b:0d:e9:ed:cf       (Unknown)
192.168.1.82       1c:1b:0d:e9:ed:cf       (Unknown)

```

(I've removed a lot of the arp-scan output.. but the point here is that I have 2 IP addresses that have the same MAC. 

It seems that Pi.Alert found the `192.168.1.67` IP first.. and now just repeatedly tells me that it has a new IP found for that MAC for the `192.168.1.82` address.

**Comment by jokob-sk** [comment]
@andrewlow 
> At least for my use case -- telling Pi.Alert that there is 1 MAC but two IP addresses .. would be ok. Or maybe I need to tell it to ignore one of the IPs?

I think your issue is different and there is a way to ignore an IP or range in the reports in the next release. Check the Events Filter setting in the dev image, I think that would help you to implement  workaround on your setup: 
![294083812-33de500f-aeab-48c7-9a2a-cdfe2ea3cb61](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c7e6f7ec-d7a3-4bf5-9234-a78683af578e)

@jsmith432 - no news for you yet, I will have to dive into the code and your settings for this one. Could you maybe send me the pialert.log (in debug mode) as well to jokob@duck.com with logs around the time when this occurred so I can debug this easier?

**Comment by jsmith432** [comment]
It seems to be reading an old value from PIHOLE, even for devices for which I set static DHCP leases. 
So, ARP and DHCP leases have the correct value, but PIHOLE read is getting old values. The pihole interface shows both IPs in the network overview, and that is the issue I am assuming.

![Screenshot 2024-01-12 001500](https://github.com/jokob-sk/Pi.Alert/assets/4900328/dc6d4389-33cd-4486-b987-fe360c1c3d15)

**Comment by jokob-sk** [comment]
Ah, that's possible - in that case, I'd try the same advice I gave above. Try deploying the `pi.alert_dev` image and try disabling event notifications on that one/two IP addresses. Or you can disable "Alert All Events" on that one device:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/ab0104b4-8548-4491-bc19-bbbef711886a)

**Comment by jsmith432** [comment]
Thanks. There are other places where this also is a problem. For example, the last IP is showing incorrectly. The old IP has not been used for over a week and is still showing for that device. I was thinking of disabling PIHOLE altogether, but that is the only place I see the containers being identified.

**Comment by jokob-sk** [comment]
You can experiment with the SQL query used to sync devices from the PiHole DB:

```
SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr is not {s-quote}00:00:00:00:00:00{s-quote}  AND na.ip is not null
```

just replace ` {s-quote}` with `'`. Please note this query will change in the next update.

**Comment by pyrodex** [comment]
I am having a similar issue and don't use PiHole DHCP but have ARP-SCAN turned on for NEW only and getting alerts for previously scanned devices when I have all the scanners set to NEW only.

![image](https://github.com/jokob-sk/Pi.Alert/assets/108703/9d3f185f-64e8-4d12-8fc8-37d20517d694)

**Comment by jokob-sk** [comment]
Hi @pyrodex ,

The event in your screenshot is a Disconnected event, not an IP-changed event, so it doesn't seem related to the current issue. Can you open a new thread with supplementary information, such as your settings for the used device scanners? This would help a lot.

Thanks in advance, 
j
