### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by hillaliy** [jokob-sk/Pi.Alert#82]
Hi,
I'm using Pi.alert for a while.
Last week started an issue, I enter the app, get the Security page, enter the password and then get an error "File not found".
I didn't change anything, WatchTower update the container Automatically.
Do you have an idea what to do?
Thanks

**Comment by jokob-sk** [comment]
Hi there!

Thanks for the message and using the container!

Is it possible you are accessing the backend by `url:port/pialert` instead
of just using `url:port`? The `/pialert` part of the URL is not necessary
anymore (it was part of the URL due to the previous use of lighttpd, which
was replaced by nginx, which is more robust).

If you still see a 404 error, can you provide me with the URL you are
trying to access and a screenshot of the network tab in the developer tools
(F12) in the browser?

Thanks in advance for helping me try to figure this one out :)

**Comment by jokob-sk** [comment]
I implemented a redirect for `root_doman/pialert` > `root_domain` so you also can try to download the newest image in about ~20min

I'll re-open the issue if the 404 is caused by something else after I receive more details

**Comment by hillaliy** [comment]
URL: http://192.168.0.10:20211
<img width="1099" alt="צילום מסך 2022-08-16 ב-14 41 18" src="https://user-images.githubusercontent.com/950010/184871126-910b56e4-fa81-470e-85e0-89094d91a873.png">

Now I don't get the error "File not found"
just get don't find page.
The autorisation is loading, I enter the password and then I get the error

**Comment by jokob-sk** [comment]
Thanks a lot for the additional details. This helped a lot.

I'm building a new image which should be live in about 15min. Please re-download the latest image and test. 

Thanks in advance!
j

**Comment by hillaliy** [comment]
Work again Thanks

**Comment by jokob-sk** [comment]
cool, thanks for the update, glad it works! :+1:
