### ISSUE TITLE
refresh list option

### ISSUE THREAD

**Issue by tamimology** [jokob-sk/Pi.Alert#91]
It seems that the refresh rate for the connected devices is being run by a crontab every 5 minutes

It would be more practical if there is a refresh button option on the devices list so that if a new device is connected it can be seen on demand, rather than waiting for the 5min to execute the cron (something similar to Fing application on android)

also to give the option to change that cron somehow using an env variable in the compose

in this, we will be having the 2 options, extended/lessen the refresh rate in cron and have an instant refresh on demand regadless

**Comment by jokob-sk** [comment]
Hi @tamimology and thanks for the suggestion!

I was thinking about on-demand scans, however the issue is that as far as I know you can't call the python script from php. The main reason seems to be that the front end (where PHP and it's user is running) doesn't have access to the '/back' folder where the python script is stored. If you happen to know how to workaround this issue, please let me know and I can try implementing it. 

Thanks!
j

**Comment by drJeckyll** [comment]
If you can live with up to one minute delay for on-demand scan and stay only with cron jobs, then there is relatively simple way to do it. 

From PHP create flag (it can be file or some db record) when user request on-demand scan. Then on every minute from cron schedule a job which will look for that flag and execute python or whatever with whatever privileges it require. And do not forget to remove flag when job is done :) Of course you can implement some flags for concurrent running if there is not any (I just don't look at code).

But it will be better if there is dedicated daemon to listen for events and then is simple to push events from PHP.
